apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: prod
  name: frontend
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      environment: prod
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: frontend
        environment: prod
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice.product-catalog.svc.cluster.local:3550
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice.currency.svc.cluster.local:7000
        - name: CART_SERVICE_ADDR
          value: cartservice.cart.svc.cluster.local:7070
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice.recommendation.svc.cluster.local:8080
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice.shipping.svc.cluster.local:50051
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice.checkout.svc.cluster.local:5050
        - name: AD_SERVICE_ADDR
          value: adservice.ad.svc.cluster.local:9555
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        image: gcr.io/GOOGLE_CLOUD_PROJECT/frontend@COMMIT_SHA
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-liveness-probe
            path: /_healthz
            port: 8080
          initialDelaySeconds: 10
        name: server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-readiness-probe
            path: /_healthz
            port: 8080
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: frontend
